<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:complexType name="IdentifiableType">
        <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
    </xs:complexType>

    <xs:simpleType name="CountryCodeType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="PostalCodeType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:pattern value="[A-Z0-9 ]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:group name="PostalCodeSpecificationGroup">
        <xs:choice>
            <xs:element name="range">
                <xs:complexType>
                    <xs:attribute name="min" type="PostalCodeType" use="required"/>
                    <xs:attribute name="max" type="PostalCodeType" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="set">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="code" type="PostalCodeType" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:choice>
    </xs:group>

    <xs:complexType name="CountrySpecificationType">
        <xs:sequence>
            <xs:element name="countryCode" type="CountryCodeType" minOccurs="0"/>
            <xs:group ref="PostalCodeSpecificationGroup" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="PositiveDecimalType">
        <xs:restriction base="xs:decimal">
            <xs:minExclusive value="0"/>
            <xs:fractionDigits value="2"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Type">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="1000"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>