<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:include schemaLocation="common.xsd"/>

    <xs:complexType name="ConsignorType">
        <xs:complexContent>
            <xs:extension base="IdentifiableType">
                <xs:sequence>
                    <xs:element name="number" type="xs:string"/>
                    <xs:element name="name" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ConsignorListType">
        <xs:sequence>
            <xs:element name="consignor" type="ConsignorType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="consignors" type="ConsignorListType"/>
</xs:schema>